<a href="https://colab.research.google.com/github/panghanwu/pytorch_example/blob/main/basic_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

In [ ]:
torch.rand(4, 3)

tensor([[0.2230, 0.0264, 0.2074],
        [0.4620, 0.5727, 0.5592],
        [0.6527, 0.7102, 0.4127],
        [0.8106, 0.2391, 0.3004]])

In [ ]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x = torch.rand(4, 3)
print(x)
print(x[1,2])

tensor([[0.3545, 0.8383, 0.5851],
        [0.3974, 0.1476, 0.7060],
        [0.7828, 0.7779, 0.1469],
        [0.9414, 0.0763, 0.1442]])
tensor(0.7060)


In [ ]:
# matrix multiply
q = x.mm(x.t())
print(q)
print(q.shape)

tensor([[1.1708, 0.6777, 1.0156, 0.4821],
        [0.6777, 0.6782, 0.5296, 0.4872],
        [1.0156, 0.5296, 1.2394, 0.8175],
        [0.4821, 0.4872, 0.8175, 0.9129]])
torch.Size([4, 4])


In [ ]:
torch_tensor = torch.randn(4, 3)
numpy_array = np.random.randn(2, 3)
print(type(torch_tensor), type(numpy_array))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [ ]:
torch_tensor = torch_tensor.numpy()
numpy_array = torch.from_numpy(numpy_array)
print(type(torch_tensor), type(numpy_array))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [ ]:
x = torch.randn(4, 3)

# run on GPU
if torch.cuda.is_available():
    x = x.cuda()
x

tensor([[-0.1406,  2.3044, -0.9438],
        [-1.1480, -0.1357, -0.9985],
        [-1.8019,  1.7025, -0.5605],
        [ 0.9448, -0.8710, -0.2713]], device='cuda:0')

In [ ]:
x.cpu()

tensor([[-0.1406,  2.3044, -0.9438],
        [-1.1480, -0.1357, -0.9985],
        [-1.8019,  1.7025, -0.5605],
        [ 0.9448, -0.8710, -0.2713]])

In [ ]:
"""Autograd"""

x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
z = y * y
print(z)
print(z.grad_fn)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)


In [ ]:
t = torch.mean(z)
print(t)
print(t.grad_fn)

tensor(9., grad_fn=<MeanBackward0>)


In [ ]:
 t.backward()
 print(z.retain_grad)
 print(y.retain_grad)
 print(x.grad)
 # only the leaf node has grad

<bound method Tensor.retain_grad of tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)>
<bound method Tensor.retain_grad of tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)>
tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [ ]:
x = torch.ones(2, 2, requires_grad=True)
s = torch.FloatTensor([[0.01,0.02]])

for i in range(10):
    s = s.mm(x)

z = torch.mean(s)
z.backward()
x.grad

tensor([[37.1200, 37.1200],
        [39.6800, 39.6800]])